language: node_js
node_js:
  - "5.10.1"
  - "4.4.3"
  - "0.12"
  - "iojs"
install:
  - npm install
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
